name: Release

on:
  push:
    tags:
      - "*"

jobs:
  push_to_registry:
    name: Push all of the registeries to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Run the pipeline
        run: docker run --rm -it $(docker build -f Dockerfile.Test .)

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Server
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.Server
          push: true
          tags: iph3i0n/effuse-server:${{ github.ref_name }}

      - name: Build and push SSO
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.SSO
          push: true
          tags: iph3i0n/effuse-sso:${{ github.ref_name }}

      - name: Build and push User Interface
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.UI
          push: true
          tags: iph3i0n/effuse-ui:${{ github.ref_name }}

